#!/usr/bin/env python3
from array import array
import sys, argparse, logging, socket, json, ssl

def sendMessage(s: socket, messageToSend: object):
  msg = (json.dumps(messageToSend) + "\n").encode()
  totalBytesSent = 0
  while totalBytesSent < len(msg):
      # send logic inspiration: https://docs.python.org/3/howto/sockets.html
      nextSent = s.send(msg[totalBytesSent:])
      if nextSent == 0:
          raise RuntimeError("lost socket connection")
      totalBytesSent = totalBytesSent + nextSent

def receieveMessage(s: socket):
  buffer = ''
  try:
      while "\n" not in buffer: 
          data = s.recv(1024).decode('utf-8')
          # buffer logic inspiration: https://stackoverflow.com/questions/55922194/python-breaks-string-after-first-character
          if not data:
              break
          buffer += data
  except Exception as loopException:
      print("Exception occurred in loop:", loopException)

  res = json.loads(buffer)
  if res['type'] != 'start' and res['type'] != 'retry' and res['type'] != 'bye' and res['type'] != 'error':
    s.close()
  return res

def runGuessLoop(s, id, wlist):
  wordsList = wlist
  res = {}
  count = 0

  while res == {} or res['type'] != 'bye':

    # filter words list based on previous guess characters' marks
    if res != {}:
      curGuess = res['guesses'][count]['word']
      guessMarks: array = res['guesses'][count]['marks']
      count += 1

      for index, mark in enumerate(guessMarks):
        if mark == 0 or mark == 1:
          wordsList = list(filter(lambda w: w[index] != curGuess[index], wordsList))
        if mark == 1:
          wordsList = list(filter(lambda w: w.find(curGuess[index]) != -1, wordsList))
        if mark == 2:
          wordsList = list(filter(lambda w: w[index] == curGuess[index], wordsList))
    
    # guess the first in words list
    guess = {"type": "guess", "id": id, "word": wordsList[0]}
    sendMessage(s, guess)

    # listen for response from server
    try:
      res = receieveMessage(s) 
    except:
      print('could not get guess response')

  print(res['flag'])


def client(args, loglevel):
  logging.basicConfig(format="%(levelname)s: %(message)s", level=loglevel)

  # turn text file into array of strings
  wordsfile = open("project1-words.txt", "r")
  wordsList = wordsfile.read().split('\n')
  wordsfile.close()

  useTLS = bool(args.tls)
  if useTLS and sys.argv.count("-p") == 0:
    port = 27994
  else:
    port = int(args.p)  

  if sys.argv.count("-s") > 0:
    sys.argv.remove('-s')
  if sys.argv.count("-p") > 0:
    sys.argv.remove('-p')
    sys.argv.remove(args.p)

  host = sys.argv[1]
  username = sys.argv[2]

  # create STREAMing socket
  sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)

  contextInstance = ssl.SSLContext()
  if useTLS:
    sslSock = contextInstance.wrap_socket(sock)

  s = sslSock if useTLS else sock

  # CONNECT
  s.connect((host, port))

  # HELLO
  try:
    hello = {"type": "hello", "northeastern_username": username}
    sendMessage(s, hello)
  except:
    print('could not send first message')

  try:  
    # START
    connectionID = receieveMessage(s)['id']

    # GUESS LOOP
    runGuessLoop(s, connectionID, wordsList)
  except:
    print('start message not receieved or guess loop error')


if __name__ == '__main__':
  parser = argparse.ArgumentParser(description='Wordle player')
  parser.add_argument('-s', dest='tls', action='store_true')
  parser.set_defaults(tls=False)
  parser.add_argument("-p", metavar="PORT", default=27993, help="pass -p with your desired TLS port")
  parser.add_argument('hostname', type=str, nargs=1, help='the hostname')
  parser.add_argument('Northeastern-username', type=str, nargs=1, help='your Northeastern username')
  
  args = parser.parse_args()
  
  loglevel = logging.INFO
  
  client(args, loglevel)